"""Generate self-contained TeX snippets from paper replay receipts."""

from __future__ import annotations

import argparse
import csv
import json
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

from .analysis_replay import replay_paper_data
from .manifest import VisualAsset, import_generator, load_visual_manifest, repository_root
from .reference import sha256_file


def _escape(value: Any) -> str:
    text = str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(character, character) for character in text)


def _assertion_lines(asset: VisualAsset, analysis: Mapping[str, Any]) -> list[str]:
    lines: list[str] = []
    headline_results = analysis.get("headline_assertions", {})
    for assertion in asset.headline_assertions:
        assertion_id = str(assertion["id"])
        result = headline_results.get(assertion_id, {})
        status = result.get("status", assertion.get("status", "declared"))
        if "actual" in result:
            detail = f"{assertion_id}: {result['actual']:.10g} ({status})"
        else:
            detail = f"{assertion_id}: {status}"
        lines.append(detail)
    return lines


def _generation_contract_lines(asset: VisualAsset) -> list[str]:
    status = str(asset.generation_contract["status"])
    operation = str(asset.generation_contract["operation"])
    return [f"generation_contract={status}: {operation}"]


def _input_lines(asset: VisualAsset, receipt: Mapping[str, Any]) -> list[str]:
    indexed = {
        (str(item["run_id"]), str(item["requested_suffix"])): item
        for item in receipt.get("inputs", ())
    }
    lines: list[str] = []
    for raw in asset.raw_inputs:
        item = indexed.get((raw.run_id, raw.member))
        if item is None:
            lines.append(f"{raw.run_id}:{raw.member} (not materialized)")
            continue
        rows = item.get("row_count")
        row_text = "n/a" if rows is None else str(rows)
        lines.append(
            f"{raw.run_id}:{raw.member}; rows={row_text}; sha256={str(item['sha256'])[:12]}"
        )
    return lines


def _box(asset: VisualAsset, lines: Sequence[str], label: str) -> str:
    body = " \\\\\n".join(_escape(line) for line in lines) or "No machine-readable rows."
    environment = "figure" if asset.kind == "figure" else "table"
    return (
        "% Generated by decaf.paper.render; no external PDF is required.\n"
        f"\\begin{{{environment}}}[htbp]\n"
        "  \\centering\n"
        "  \\fbox{\\begin{minipage}{0.94\\linewidth}\n"
        f"    \\textbf{{{_escape(label)}}}\\\\\n"
        f"    {body}\n"
        "  \\end{minipage}}\n"
        f"  \\caption{{{_escape(asset.title)}}}\n"
        f"  \\label{{{_escape('decaf:' + asset.asset_id)}}}\n"
        f"\\end{{{environment}}}\n"
    )


def render_data_asset(
    asset: VisualAsset, receipt: Mapping[str, Any], analysis: Mapping[str, Any]
) -> str:
    """Render a provenance-backed data asset as a standalone TeX snippet."""

    lines = (
        _generation_contract_lines(asset)
        + _input_lines(asset, receipt)
        + _assertion_lines(asset, analysis)
    )
    return _box(asset, lines, "Sealed replay summary")


def render_registry_table(
    asset: VisualAsset, receipt: Mapping[str, Any], analysis: Mapping[str, Any]
) -> str:
    """Render a registry/configuration-backed table without manual entries."""

    lines = (
        _generation_contract_lines(asset)
        + _input_lines(asset, receipt)
        + _assertion_lines(asset, analysis)
    )
    return _box(asset, lines, "Generated registry summary")


def render_source_missing_asset(
    asset: VisualAsset, receipt: Mapping[str, Any], analysis: Mapping[str, Any]
) -> str:
    """Render an explicit placeholder when the historical paper source is absent."""

    del receipt, analysis
    note = asset.source_note or "Historical source was not recovered."
    return _box(asset, ["status=source_missing", note], "Source unavailable")


def render_all(
    replay_root: str | Path,
    *,
    repo_root: str | Path | None = None,
    generated_root: str | Path | None = None,
) -> list[Path]:
    """Generate all 28 TeX assets using only replay receipts and copied data."""

    repo = Path(repo_root).resolve() if repo_root else repository_root()
    replay = Path(replay_root).resolve()
    receipt = json.loads((replay / "replay_receipt.json").read_text(encoding="utf-8"))
    analysis = receipt
    manifest = load_visual_manifest(repo / "paper" / "visual_manifest.yaml")
    output = Path(generated_root).resolve() if generated_root else repo
    paths: list[Path] = []
    artifact_rows: list[dict[str, Any]] = []
    for asset in manifest.assets.values():
        generator = import_generator(asset.generator)
        content = generator(asset, receipt, analysis)
        if generated_root:
            subdirectory = "figures" if asset.kind == "figure" else "tables"
            destination = output / subdirectory / Path(asset.tex_target).name
        else:
            destination = output / asset.tex_target
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8")
        paths.append(destination)
        artifact_rows.append(
            {
                "asset_id": asset.asset_id,
                "kind": asset.kind,
                "number": asset.number,
                "manifest_status": asset.status,
                "generated_path": destination.relative_to(output).as_posix(),
                "generated_sha256": sha256_file(destination),
                "generated_bytes": destination.stat().st_size,
                "comparison_status": (
                    "historical_source_missing"
                    if asset.status == "source_missing"
                    else "generated_without_frozen_tex_baseline"
                ),
            }
        )
    verification = replay / "verification"
    verification.mkdir(parents=True, exist_ok=True)
    columns = [
        "asset_id",
        "kind",
        "number",
        "manifest_status",
        "generated_path",
        "generated_sha256",
        "generated_bytes",
        "comparison_status",
    ]
    with (verification / "paper_artifact_diff.csv").open(
        "w", encoding="utf-8", newline=""
    ) as handle:
        writer = csv.DictWriter(handle, fieldnames=columns)
        writer.writeheader()
        writer.writerows(artifact_rows)
    return paths


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reference-root", action="append", help="Recursive archive search root")
    parser.add_argument("--replay-root", required=True, help="Replay output directory")
    parser.add_argument("--repo-root", help="Repository root containing paper manifests")
    parser.add_argument("--generated-root", help="Alternative root for generated TeX snippets")
    parser.add_argument(
        "--render-only", action="store_true", help="Reuse an existing replay receipt"
    )
    parser.add_argument("--materialize-only", action="store_true", help="Skip TeX generation")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.render_only and args.materialize_only:
        raise SystemExit("--render-only and --materialize-only are mutually exclusive")
    repo = Path(args.repo_root).resolve() if args.repo_root else repository_root()
    if not args.render_only:
        roots: Any = args.reference_root if args.reference_root else None
        replay_paper_data(args.replay_root, reference_root=roots, repo_root=repo)
    if not args.materialize_only:
        render_all(
            args.replay_root,
            repo_root=repo,
            generated_root=args.generated_root,
        )
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())


__all__ = [
    "build_parser",
    "main",
    "render_all",
    "render_data_asset",
    "render_registry_table",
    "render_source_missing_asset",
]
